
baseDomain: semaan.ca
geoDomain: v3geo-test.semaan.ca

controlRegion:
  name: control
  nodeSelectorConfig:
    key: kubernetes.io/hostname
    value: afn-v3-test-control

regions:
  - name: north-america
    nodeSelector:
      kubernetes.io/hostname: afn-v3-test-srv-mia-1
  - name: europe
    nodeSelector:
      kubernetes.io/hostname: afn-v3-test-srv-mil-1

dnsRegions:
  - name: north-america
    target: north-america
    default: true
  - name: europe
    target: europe

api:
  bucket: afn-test-23d9g


lb:
  app:
    domain: lb-app.v3geo-test.semaan.ca
  realtime: 
    domain: lb-realtime.v3geo-test.semaan.ca
  pages:
    domain: lb-pages.v3geo-test.semaan.ca
  admin:
    domain: lb-admin.v3geo-test.semaan.ca
  api:
    domain: lb-api.v3geo-test.semaan.ca

