sources:
  - node
  - service
  - crd

provider: linode

linode:
  secretName: linode-api-token

logLevel: trace

domainFilters: 
  - semaan.ca

fqdnTemplates:
  - "{{.Name}}.v3geo.semaan.ca"

policy: sync

crd:
  create: true

rbac:
  create: true

logLevel: trace

managedRecordTypesFilters:
  - A
  - CNAME
  - NS

txtOwnerId: main
