- name: Setup basic control plane
  hosts: controlPlane
  tasks:
  - name: Find netmaker IP
    shell: |
      set -o pipefail && ip a show dev netmaker | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sed 's/inet //'
    args:
      executable: /usr/bin/bash
    register: netmaker_ip

  - name: Install k3s server
    shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip {{ netmaker_ip.stdout }} --node-external-ip {{ ipv4[0] }} --flannel-iface netmaker --disable=traefik" sh -

  - name: Add netmaker check ExecStartPre
    shell: |
      grep 'ExecStartPre=/usr/sbin/ip a show dev netmaker' /etc/systemd/system/k3s.service || echo 'ExecStartPre=/usr/sbin/ip a show dev netmaker' >> /etc/systemd/system/k3s.service 

  - name: Systemd reload
    command: systemctl daemon-reload
