- name: Basic setup
  hosts: controlPlane:workerNode
  tasks:
  - name: Set hostname
    command: hostnamectl set-hostname {{inventory_hostname}}
  - name: Stop systemd-resolved
    command: systemctl stop systemd-resolved.service
  - name: Disable systemd-resolved
    command: systemctl disable systemd-resolved.service
  - name: Mask systemd-resolved
    command: systemctl mask systemd-resolved.service
  - name: Remove /etc/resolv.conf symlink
    command: rm /etc/resolv.conf
  - name: Configure /etc/resolv.conf
    shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf
  - name: Setup cron to watch flannel failure and restart k3s
    shell: |
      echo '*/5 * * * * root /bin/bash -c "if ! ip route | /usr/bin/grep flannel; then /usr/bin/systemctl restart k3s-agent.service; fi"' > /etc/cron.d/watchdog-flannel

- name: Setup control plane
  import_playbook: control-plane.yaml

- name: Setup worker nodes
  import_playbook: worker-nodes.yaml

- name: Setup monit
  import_playbook: monit.yaml

