- name: Get join token
  hosts: controlPlane
  tasks:
  - name: Get join token from control plane node
    shell: |
      cat /var/lib/rancher/k3s/server/token | tr -d '\n'
    register: join_token

- name: Join worker nodes to netmaker
  hosts: workerNode
  tasks:
  - name: Install k3s agent
    shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://{{hostvars[groups['controlPlane'][0]]['ansible_default_ipv4']['address']}}:6443 --token {{hostvars[groups['controlPlane'][0]]["join_token"].stdout}} --node-ip {{ ansible_eth0.ipv4.address }} --node-external-ip {{ ansible_eth0.ipv4.address }}" sh -



