# Default values for afn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

geoDomain: DOMAIN_NAME
dnsRegions: []
lb:
  imagePullSecrets: []
  image:
    repository: caddy
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.7"
  pages:
    image:
      repository: ghcr.io/julsemaan/anyfile-notepad/pages
      tag: 216cd7c0ce733666b1bf5e2e8e3eaacce458f782
      pullPolicy: IfNotPresent
    domain: pages.DOMAIN_NAME
  admin:
    image:
      repository: ghcr.io/julsemaan/anyfile-notepad/admin
      tag: 216cd7c0ce733666b1bf5e2e8e3eaacce458f782
      pullPolicy: IfNotPresent
    domain: admin.DOMAIN_NAME
  app:
    domain: app.DOMAIN_NAME
  api:
    domain: api.DOMAIN_NAME
  realtime:
    domain: realtime.DOMAIN_NAME
    region: null
api:
  image:
    repository: ghcr.io/julsemaan/anyfile-notepad/api
    tag: b13e4aec2f0c3f0b1688397705ce92acd5e5b61a
    pullPolicy: IfNotPresent
backend:
  image:
    repository: ghcr.io/julsemaan/anyfile-notepad/webserver
    tag: 216cd7c0ce733666b1bf5e2e8e3eaacce458f782
    pullPolicy: IfNotPresent
  appProdImage:
    repository: ghcr.io/julsemaan/anyfile-notepad/client-light
    tag: "216cd7c0ce733666b1bf5e2e8e3eaacce458f782"
    pullPolicy: IfNotPresent
  appDevImage:
    repository: ghcr.io/julsemaan/anyfile-notepad/client-light
    tag: 216cd7c0ce733666b1bf5e2e8e3eaacce458f782
    pullPolicy: IfNotPresent
geodns:
  imagePullSecrets: []
  image:
    repository: ghcr.io/julsemaan/afn-k8s/geodns
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "72c532175b2ec5c5ffeacc090e24775a68670be8"
rsyslog:
  imagePullSecrets: []
  image:
    repository: ghcr.io/julsemaan/afn-k8s/rsyslog
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1c2ea7e4fff75d3dd1c13bdfd5520bfd8176fa92"
controlRegion: {}
regions: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
#test
