# Default values for afn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

geoDomain: DOMAIN_NAME
dnsRegions: []
lb:
  imagePullSecrets: []
  image:
    repository: caddy
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.7"
  pages:
    image:
      repository: ghcr.io/julsemaan/anyfile-notepad/pages
      tag: 7f2da3a84656896314011ae968778f4ce9300383
      pullPolicy: IfNotPresent
    domain: pages.DOMAIN_NAME
  admin:
    image:
      repository: ghcr.io/julsemaan/anyfile-notepad/admin
      tag: 216cd7c0ce733666b1bf5e2e8e3eaacce458f782
      pullPolicy: IfNotPresent
    domain: admin.DOMAIN_NAME
  app:
    domain: app.DOMAIN_NAME
  realtime:
    domain: realtime.DOMAIN_NAME
    region: null
backend:
  imagePullSecrets: []
  image:
    repository: ghcr.io/julsemaan/anyfile-notepad/webserver
    tag: 7f2da3a84656896314011ae968778f4ce9300383
    pullPolicy: IfNotPresent
  appProdImage:
    repository: ghcr.io/julsemaan/anyfile-notepad/client-light
    tag: "7f2da3a84656896314011ae968778f4ce9300383"
    pullPolicy: IfNotPresent
  appDevImage:
    repository: ghcr.io/julsemaan/anyfile-notepad/client-light
    tag: 7f2da3a84656896314011ae968778f4ce9300383
    pullPolicy: IfNotPresent
geodns:
  imagePullSecrets: []
  image:
    repository: julsemaan/geodns
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
controlRegion: {}
regions: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
