---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@{{ .Values.geoDomain }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        webhook:
          solverName: linode
          groupName: acme.slicen.me
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@{{ .Values.geoDomain }}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        webhook:
          solverName: linode
          groupName: acme.slicen.me

