
{{- define "afn.node-exporter" -}}
{{- $context := index . "context" }}
{{- $type := index . "type" }}
{{- $controlPlane := eq $type "control-plane" }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter-{{ $type }}
  name: node-exporter-{{ $type }}
  namespace: {{ $context.Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter-{{ $type }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: node-exporter-{{ $type }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  {{- if $controlPlane }}
                  operator: Exists
                  {{- else }}
                  operator: DoesNotExist
                  {{- end }}
      containers:
      - args:
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
        - --collector.netclass.ignored-devices=^(veth.*)$
        name: node-exporter
        image: prom/node-exporter
        ports:
          - containerPort: 9100
            hostPort: 9100
            hostIP: 169.254.20.10
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        volumeMounts:
        - mountPath: /host/sys
          mountPropagation: HostToContainer
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      volumes:
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
{{- if $controlPlane }}
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-{{ $type }}
  namespace: {{ $context.Release.Namespace }}
  annotations:
    prometheus.io/instance: control-plane.{{ $context.Values.geoDomain }}
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9100'
spec:
  ports:
  - port: 9100
    name: metrics
  selector:
    app.kubernetes.io/name: node-exporter-{{ $type }}
{{- end }}
{{- end }}

{{ include "afn.node-exporter" (dict "context" . "type" "control-plane") }}
{{ include "afn.node-exporter" (dict "context" . "type" "workers") }}

