---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "afn.fullname" . }}-syslog
  labels:
    app: rsyslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      containers:
      - name: rsyslog
        image: julsemaan/rsyslog
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 514
          protocol: TCP
        - containerPort: 514
          protocol: UDP
        volumeMounts:
        - mountPath: /logs
          name: logs
      volumes:
        - name: logs
          hostPath:
            path: /mnt/logs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsyslog
  name: {{ include "afn.fullname" . }}-syslog
spec:
  selector:
    app: rsyslog
  ports:
    - protocol: TCP
      name: rsyslog
      port: 514
      targetPort: 514
    - protocol: UDP
      name: rsyslog-udp
      port: 514
      targetPort: 514
