{{ $context := merge (dict "appName" "rsyslog") . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-{{ include "afn.fullname" . }}
  labels:
    {{- include "afn.app-selectorLabels" $context | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "afn.app-selectorLabels" $context | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "afn.app-selectorLabels" $context | nindent 8 }}
    spec:
      {{- with .Values.rsyslog.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $context.Values.rsyslog.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $context.Values.rsyslog.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $context.Values.rsyslog.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $context.Values.rsyslog.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "afn.serviceAccountName" $context }}
      containers:
      - name: rsyslog
        securityContext:
          {{- toYaml $context.Values.rsyslog.securityContext | nindent 10 }}
        image: "{{ .Values.rsyslog.image.repository }}:{{ .Values.rsyslog.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.rsyslog.image.pullPolicy }}
        ports:
        - containerPort: 514
          protocol: TCP
        - containerPort: 514
          protocol: UDP
        volumeMounts:
        - mountPath: /logs
          name: logs
        resources:
          {{- toYaml $context.Values.rsyslog.resources | nindent 12 }}
      volumes:
        - name: logs
          hostPath:
            path: /mnt/logs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog-{{ include "afn.fullname" $context }}
  namespace: {{ $context.Release.Namespace }}
spec:
  selector:
    {{- include "afn.app-selectorLabels" $context | nindent 4 }}
  ports:
    - protocol: TCP
      name: rsyslog
      port: 514
      targetPort: 514
    - protocol: UDP
      name: rsyslog-udp
      port: 514
      targetPort: 514
