---
apiVersion: v1
kind: Secret
metadata:
  name: linode-api-token
  namespace: afn
stringData:
  linode_api_token: $LINODE_ACCESS_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: linode-credentials
stringData:
  token: $LINODE_ACCESS_TOKEN
