name: Deploy afn-capl

on:
  workflow_dispatch:
    branches: ['**']
    inputs:
      environment:
        type: environment


jobs:
  deployment:
    environment: ${{ github.event.inputs.environment || 'main' }}
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ env.KUBECONFIG_B64 }}

    - uses: 'vimeda/helm@v1.7.0'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: clusterctl-save-${{ github.event.inputs.environment }}

    - run: mv clusterctl-save-${{ github.event.inputs.environment }} capi/.clusterctl-save
    
    - run: make -C capi clusterctl-init
    - run: make -C capi clusterctl-restore
    - run: make -C capi helm-install-afn-capl
    - run: make -C capi clusterctl-wait
    - run: make -C capi clusterctl-save

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: clusterctl-save-${{ github.event.inputs.environment }}
        path: |
          capi/.clusterctl-save
