name: Deploy AFN base dependencies

on:
  workflow_dispatch:
    branches: ['**']


jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: create ns afn

    - name: 'Deploy nodelocaldns'
      uses: 'vimeda/helm@v1.7.0'
      with:
        release: 'nodelocaldns'
        namespace: 'kube-system'
        chart: 'charts/nodelocaldns'
        value-files: >-
          [
            "afn-values.yaml"
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
    - name: 'Deploy external-dns'
      uses: 'vimeda/helm@v1.7.0'
      with:
        release: 'external-dns'
        namespace: 'afn'
        chart: 'oci://registry-1.docker.io/bitnamicharts/external-dns'
        value-files: >-
          [
            "external-dns-values.yaml"
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

    - name: 'Deploy cert-manager'
      uses: 'vimeda/helm@v1.7.0'
      with:
        release: 'cert-manager'
        namespace: 'cert-manager'
        chart: 'jetstack/cert-manager'
        chart-version: v1.13.1
        repo: 'https://charts.jetstack.io'
        repo-alias: jetstack
        values: |
          installCRDs: true
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

    - name: 'Deploy cert-manager-webhook-linode'
      uses: 'vimeda/helm@v1.7.0'
      with:
        release: 'cert-manager-webhook-linode'
        namespace: 'cert-manager'
        chart: 'https://github.com/slicen/cert-manager-webhook-linode/releases/download/v0.2.0/cert-manager-webhook-linode-v0.2.0.tgz'
        values: |
          deployment:
            logLevel: null
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

