name: Deploy AFN base dependencies

on:
  workflow_dispatch:
    branches: ['**']


jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: 'Deploy'
      uses: 'vimeda/helm@v1.7.0'
      with:
        release: 'cert-manager'
        namespace: 'cert-manager'
        chart: 'jetstack/cert-manager'
        chart-version: v1.13.1
        token: '${{ github.token }}'
        repo: 'https://charts.jetstack.io'
        repo-alias: jetstack
        values: |
          installCRDs: true
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

