name: Deploy AFN helm chart

on:
  push:
    branches: ['main']
    paths:
      - 'charts/afn/**'
      - '.github/workflows/deploy-afn.yml'
  workflow_dispatch:
    branches: ['**']
    inputs:
      environment:
        type: environment

concurrency:
  group: deployments
  cancel-in-progress: false

jobs:
  deployment:
    environment: ${{ github.event.inputs.environment || "main" }}
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: 'Deploy'
      uses: 'vimeda/helm@v1.7.0'
      with:
        release: 'afn'
        namespace: 'afn'
        chart: 'charts/afn'
        token: '${{ github.token }}'
        timeout: 10m
        value-files: >-
          [
            "afn-values.yaml"
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
