name: Deploy

on:
  workflow_dispatch:
    branches: ['**']


jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'afn'
        namespace: 'afn'
        chart: 'charts/afn'
        token: '${{ github.token }}'
        value-files: >-
        [
          "afn-values.yaml"
        ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
