name: Deploy AFN ansible playbooks (k3s)

on:
  workflow_dispatch:
    branches: ['**']
    inputs:
      environment:
        type: environment


jobs:
  deployment:
    environment: ${{ github.event.inputs.environment || 'main' }}
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Install linode_api4
      run: pipx inject ansible-core linode_api4
    
    - name: Setup secret/sasl_passwd.db
      run: |
        mkdir -p secret/
        echo ${{secrets.SASL_PASSWD}} | base64 -d > secret/sasl_passwd.db

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: infra/k3s.yaml
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}
        requirements: infra/requirements.yaml
        # Optional, additional flags to pass to ansible-playbook
        options: |
          -e netclient_token=${{secrets.NETCLIENT_TOKEN}}
          --inventory infra/inventory_linode.yaml
          --verbose
      env:
        LINODE_ACCESS_TOKEN: ${{secrets.LINODE_ACCESS_TOKEN}}
