---
name: Deploy AFN VMs

on:
  workflow_dispatch:
    branches: ['**']
    inputs:
      environment:
        type: environment


jobs:
  deployment:
    environment: ${{ github.event.inputs.environment || 'main' }}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Install linode_api4
        run: pipx inject ansible-core linode_api4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: infra/linodes.yaml
          vault_password: ${{secrets.VAULT_PASS}}
          requirements: infra/requirements.yaml
          # Optional, additional flags to pass to ansible-playbook
          options: |
            -e @${{vars.INFRA_VARS}}
            -e prefix=${{vars.INFRA_PREFIX}}
            -e token=${{secrets.LINODE_ACCESS_TOKEN}}
            --verbose

